### ISSUE TITLE
同一コードネームの省略

### ISSUE THREAD

**Issue by chaos-rfk** [rkmathi/vocarus-2#6]
同じコードネームが連続するときは最初の１個目だけを表示するようにできませんでしょうか。
例：
☆現在：C F F F C
→修正後：C F　　   C
よろしくお願いします。

**Comment by yoavlt** [comment]
前のコードと一致しない時に表示するように修正しました。

**Comment by rkmathi** [comment]
まちがえてReopenしてもうた(；´Д｀)
